import { BidItem } from './types';

export const DUMMY_BID_DATA: BidItem[] = [
  // 인공지능 관련 공고 (신규_공용_그룹_2024_04_15)
  {
    id: 1,
    title: '인공지능 기반 데이터 분석 솔루션 개발',
    organization: '한국정보화진흥원',
    budget: '3억 5천만원',
    deadline: '2025-05-15',
    publishedDate: '2025-04-23',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 2,
    title: '인공지능 챗봇 서비스 구축 사업',
    organization: '서울특별시',
    budget: '2억 8천만원',
    deadline: '2025-04-30',
    publishedDate: '2025-04-22',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 3,
    title: '인공지능 기반 스마트 팩토리 시스템 개발',
    organization: '중소벤처기업부',
    budget: '5억 2천만원',
    deadline: '2025-05-20',
    publishedDate: '2025-04-20',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 4,
    title: '인공지능 영상 인식 시스템 구축',
    organization: '경기도청',
    budget: '4억원',
    deadline: '2025-06-15',
    publishedDate: '2025-04-18',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 5,
    title: '인공지능 자연어 처리 플랫폼 구축',
    organization: '국립국어원',
    budget: '2억 5천만원',
    deadline: '2025-05-10',
    publishedDate: '2025-04-15',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 6,
    title: '인공지능 기반 민원 응대 시스템 구축',
    organization: '행정안전부',
    budget: '3억 8천만원',
    deadline: '2025-04-28',
    publishedDate: '2025-04-10',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 7,
    title: '인공지능 활용 교통 예측 시스템 구축',
    organization: '국토교통부',
    budget: '4억 5천만원',
    deadline: '2025-05-25',
    publishedDate: '2025-04-08',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 8,
    title: '인공지능 기반 사이버 보안 시스템 개발',
    organization: '과학기술정보통신부',
    budget: '6억원',
    deadline: '2025-06-10',
    publishedDate: '2025-04-03',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: true,
  },
  {
    id: 9,
    title: '인공지능 의료 영상 분석 시스템 구축',
    organization: '보건복지부',
    budget: '7억 2천만원',
    deadline: '2025-05-30',
    publishedDate: '2025-03-28',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 10,
    title: '인공지능 기반 스마트 농업 시스템 개발',
    organization: '농림축산식품부',
    budget: '3억 2천만원',
    deadline: '2025-04-29',
    publishedDate: '2025-03-24',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },

  // 빅데이터 관련 공고 (신규_공용_그룹_2024_06_22)
  {
    id: 11,
    title: '빅데이터 플랫폼 구축 사업',
    organization: '한국데이터산업진흥원',
    budget: '8억원',
    deadline: '2025-06-30',
    publishedDate: '2025-04-01',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 12,
    title: '빅데이터 기반 마케팅 분석 시스템 개발',
    organization: '한국관광공사',
    budget: '4억 3천만원',
    deadline: '2025-07-15',
    publishedDate: '2025-03-15',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 13,
    title: '빅데이터 활용 상권 분석 시스템 구축',
    organization: '중소벤처기업진흥공단',
    budget: '3억 7천만원',
    deadline: '2025-06-28',
    publishedDate: '2025-02-20',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 14,
    title: '빅데이터 분석 환경 구축 사업',
    organization: '통계청',
    budget: '6억 5천만원',
    deadline: '2025-07-20',
    publishedDate: '2025-02-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 15,
    title: '공공 빅데이터 활용 플랫폼 개발',
    organization: '행정안전부',
    budget: '7억 8천만원',
    deadline: '2025-06-25',
    publishedDate: '2025-01-15',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 16,
    title: '빅데이터 기반 정책 지원 시스템 구축',
    organization: '국무조정실',
    budget: '5억 4천만원',
    deadline: '2025-07-05',
    publishedDate: '2025-04-19',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 17,
    title: '빅데이터 분석을 통한 에너지 효율화 시스템 개발',
    organization: '한국에너지공단',
    budget: '4억 9천만원',
    deadline: '2025-06-22',
    publishedDate: '2025-04-21',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 18,
    title: '빅데이터 기반 환경 모니터링 시스템 구축',
    organization: '환경부',
    budget: '6억 2천만원',
    deadline: '2025-07-10',
    publishedDate: '2025-04-17',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 19,
    title: '빅데이터 분석을 통한 교통 최적화 시스템 개발',
    organization: '서울교통공사',
    budget: '5억 8천만원',
    deadline: '2025-06-20',
    publishedDate: '2025-04-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 20,
    title: '빅데이터 기반 관광 분석 플랫폼 구축',
    organization: '문화체육관광부',
    budget: '3억 9천만원',
    deadline: '2025-07-25',
    publishedDate: '2025-03-10',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 클라우드 관련 공고 (신규_공용_그룹_2024_09_10)
  {
    id: 21,
    title: '클라우드 기반 업무 환경 구축',
    organization: '행정안전부',
    budget: '5억원',
    deadline: '2025-09-30',
    publishedDate: '2025-04-22',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 22,
    title: '공공 클라우드 서비스 구축 사업',
    organization: '과학기술정보통신부',
    budget: '9억 5천만원',
    deadline: '2025-10-15',
    publishedDate: '2025-04-16',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: true,
  },
  {
    id: 23,
    title: '클라우드 데이터 센터 구축',
    organization: '한국정보화진흥원',
    budget: '12억원',
    deadline: '2025-09-25',
    publishedDate: '2025-04-11',
    status: '공사',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 24,
    title: '클라우드 기반 교육 플랫폼 개발',
    organization: '교육부',
    budget: '4억 8천만원',
    deadline: '2025-10-05',
    publishedDate: '2025-03-25',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 25,
    title: '금융 클라우드 서비스 구축',
    organization: '금융위원회',
    budget: '7억 6천만원',
    deadline: '2025-09-20',
    publishedDate: '2025-02-14',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: true,
  },
  {
    id: 26,
    title: '클라우드 기반 스마트시티 통합 플랫폼 개발',
    organization: '국토교통부',
    budget: '10억 2천만원',
    deadline: '2025-10-10',
    publishedDate: '2025-09-12',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 27,
    title: '클라우드 기반 재난 관리 시스템 구축',
    organization: '소방청',
    budget: '6억 8천만원',
    deadline: '2025-09-28',
    publishedDate: '2025-09-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 28,
    title: '의료 클라우드 서비스 구축',
    organization: '보건복지부',
    budget: '8억 3천만원',
    deadline: '2025-10-20',
    publishedDate: '2025-09-18',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: true,
  },
  {
    id: 29,
    title: '클라우드 기반 지능형 행정 서비스 구축',
    organization: '서울특별시',
    budget: '5억 7천만원',
    deadline: '2025-09-15',
    publishedDate: '2025-09-01',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 30,
    title: '클라우드 컴퓨팅 인프라 구축',
    organization: '한국정보통신진흥협회',
    budget: '11억원',
    deadline: '2025-10-25',
    publishedDate: '2025-09-20',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 핀테크/금융 관련 공고 (신규_공용_그룹_2025_01_04)
  {
    id: 31,
    title: '핀테크 혁신 서비스 개발 지원 사업',
    organization: '금융위원회',
    budget: '6억원',
    deadline: '2026-01-30',
    publishedDate: '2026-01-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 32,
    title: '디지털 금융 플랫폼 구축 사업',
    organization: '한국은행',
    budget: '9억 8천만원',
    deadline: '2026-02-15',
    publishedDate: '2026-01-10',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 33,
    title: '핀테크 창업 지원 센터 구축',
    organization: '중소벤처기업부',
    budget: '7억 2천만원',
    deadline: '2026-01-25',
    publishedDate: '2026-01-03',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 34,
    title: '블록체인 기반 금융 거래 시스템 개발',
    organization: '금융결제원',
    budget: '8억 5천만원',
    deadline: '2026-02-10',
    publishedDate: '2026-01-12',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 35,
    title: '금융 빅데이터 분석 시스템 구축',
    organization: '금융감독원',
    budget: '7억 9천만원',
    deadline: '2026-01-20',
    publishedDate: '2026-01-02',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 36,
    title: '핀테크 보안 솔루션 개발',
    organization: '과학기술정보통신부',
    budget: '5억 4천만원',
    deadline: '2026-02-05',
    publishedDate: '2026-01-08',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 37,
    title: '디지털 화폐 시스템 구축',
    organization: '한국은행',
    budget: '12억원',
    deadline: '2026-01-28',
    publishedDate: '2026-01-04',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 38,
    title: '금융 클라우드 보안 시스템 개발',
    organization: '금융보안원',
    budget: '6억 3천만원',
    deadline: '2026-02-20',
    publishedDate: '2026-01-15',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 39,
    title: '핀테크 기반 중소기업 대출 시스템 구축',
    organization: '신용보증기금',
    budget: '4억 9천만원',
    deadline: '2026-01-15',
    publishedDate: '2026-01-01',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 40,
    title: '금융 데이터 거래소 구축 사업',
    organization: '한국데이터산업진흥원',
    budget: '8억 1천만원',
    deadline: '2026-02-25',
    publishedDate: '2026-01-18',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 보안/인증 관련 공고 (신규_공용_그룹_2025_03_15)
  {
    id: 41,
    title: '공공기관 사이버 보안 시스템 구축',
    organization: '행정안전부',
    budget: '7억원',
    deadline: '2026-03-30',
    publishedDate: '2026-03-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 42,
    title: '생체인증 기반 접근 제어 시스템 개발',
    organization: '법무부',
    budget: '5억 6천만원',
    deadline: '2026-04-15',
    publishedDate: '2026-03-10',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: true,
  },
  {
    id: 43,
    title: '국가 정보보안 인증 체계 구축',
    organization: '국가정보원',
    budget: '9억 3천만원',
    deadline: '2026-03-25',
    publishedDate: '2026-03-02',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 44,
    title: '블록체인 기반 전자 인증 시스템 개발',
    organization: '과학기술정보통신부',
    budget: '6억 8천만원',
    deadline: '2026-04-10',
    publishedDate: '2026-03-12',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 45,
    title: '지능형 보안관제 시스템 구축',
    organization: '한국인터넷진흥원',
    budget: '8억 5천만원',
    deadline: '2026-03-20',
    publishedDate: '2026-03-01',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: true,
  },
  {
    id: 46,
    title: '금융권 인증 보안 시스템 개발',
    organization: '금융보안원',
    budget: '7억 2천만원',
    deadline: '2026-04-05',
    publishedDate: '2026-03-08',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 47,
    title: '클라우드 보안 인증 시스템 구축',
    organization: '한국정보통신기술협회',
    budget: '5억 9천만원',
    deadline: '2026-03-28',
    publishedDate: '2026-03-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 48,
    title: '공공 인증서 관리 시스템 개발',
    organization: '행정안전부',
    budget: '4억 7천만원',
    deadline: '2026-04-20',
    publishedDate: '2026-03-15',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 49,
    title: '네트워크 보안 장비 도입',
    organization: '국방부',
    budget: '11억원',
    deadline: '2026-03-15',
    publishedDate: '2026-03-01',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 50,
    title: '보안 관제 통합 플랫폼 구축',
    organization: '경찰청',
    budget: '8억 2천만원',
    deadline: '2026-04-25',
    publishedDate: '2026-03-18',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 통신 관련 공고 (신규_공용_개인_2024_03_12)
  {
    id: 51,
    title: '5G 기반 공공 네트워크 구축 사업',
    organization: '과학기술정보통신부',
    budget: '15억원',
    deadline: '2025-03-30',
    publishedDate: '2025-03-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 52,
    title: '통신망 고도화 사업',
    organization: '한국정보통신진흥협회',
    budget: '9억 8천만원',
    deadline: '2025-04-15',
    publishedDate: '2025-03-10',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 53,
    title: '스마트시티 통신 인프라 구축',
    organization: '국토교통부',
    budget: '12억 3천만원',
    deadline: '2025-03-25',
    publishedDate: '2025-03-02',
    status: '공사',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 54,
    title: '농어촌 통신망 확충 사업',
    organization: '농림축산식품부',
    budget: '7억 8천만원',
    deadline: '2025-04-10',
    publishedDate: '2025-03-12',
    status: '공사',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 55,
    title: '차세대 무선통신 시험망 구축',
    organization: '한국전자통신연구원',
    budget: '14억 5천만원',
    deadline: '2025-03-20',
    publishedDate: '2025-03-01',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 56,
    title: '공공 와이파이 확대 구축 사업',
    organization: '서울특별시',
    budget: '6억 2천만원',
    deadline: '2025-04-05',
    publishedDate: '2025-03-08',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 57,
    title: '해상 통신망 구축 사업',
    organization: '해양수산부',
    budget: '11억 7천만원',
    deadline: '2025-03-28',
    publishedDate: '2025-03-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 58,
    title: '재난 안전 통신망 확충',
    organization: '행정안전부',
    budget: '13억 9천만원',
    deadline: '2025-04-20',
    publishedDate: '2025-03-15',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 59,
    title: 'IoT 기반 스마트 그리드 통신망 구축',
    organization: '산업통상자원부',
    budget: '8억 4천만원',
    deadline: '2025-03-15',
    publishedDate: '2025-03-01',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 60,
    title: '위성통신 지상국 시설 구축',
    organization: '한국항공우주연구원',
    budget: '18억 2천만원',
    deadline: '2025-04-25',
    publishedDate: '2025-03-18',
    status: '공사',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 추가 데이터 (신규_공용_개인_2024_05_20 - 네트워크 관련)
  {
    id: 61,
    title: '네트워크 보안 장비 교체 사업',
    organization: '국가정보자원관리원',
    budget: '7억 5천만원',
    deadline: '2025-06-15',
    publishedDate: '2025-05-15',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 62,
    title: '네트워크 통합 관리 시스템 구축',
    organization: '한국인터넷진흥원',
    budget: '6억 8천만원',
    deadline: '2025-05-30',
    publishedDate: '2025-05-10',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 63,
    title: '광역 네트워크 인프라 확충 사업',
    organization: '과학기술정보통신부',
    budget: '15억 2천만원',
    deadline: '2025-06-25',
    publishedDate: '2025-05-20',
    status: '공사',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 64,
    title: '기관 네트워크 트래픽 분석 시스템 도입',
    organization: '국세청',
    budget: '4억 7천만원',
    deadline: '2025-05-25',
    publishedDate: '2025-05-05',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 65,
    title: '지자체 네트워크 연계 시스템 구축',
    organization: '행정안전부',
    budget: '9억 3천만원',
    deadline: '2025-06-10',
    publishedDate: '2025-05-12',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 66,
    title: '네트워크 장비 통합 유지보수',
    organization: '교육부',
    budget: '5억 1천만원',
    deadline: '2025-05-28',
    publishedDate: '2025-05-08',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 67,
    title: 'SDN 기반 네트워크 인프라 구축',
    organization: '한국전자통신연구원',
    budget: '8억 7천만원',
    deadline: '2025-06-20',
    publishedDate: '2025-05-18',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 68,
    title: '차세대 네트워크 기술 연구개발',
    organization: '과학기술정보통신부',
    budget: '11억 5천만원',
    deadline: '2025-06-05',
    publishedDate: '2025-05-01',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 69,
    title: '네트워크 모니터링 시스템 고도화',
    organization: '한국정보통신진흥협회',
    budget: '4억 9천만원',
    deadline: '2025-05-20',
    publishedDate: '2025-05-03',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 70,
    title: '스마트 캠퍼스 네트워크 구축 사업',
    organization: '서울대학교',
    budget: '7억 4천만원',
    deadline: '2025-06-30',
    publishedDate: '2025-05-25',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 가상현실/VR 관련 공고 (신규_공용_개인_2024_08_15)
  {
    id: 71,
    title: '가상현실 기반 교육 플랫폼 개발',
    organization: '교육부',
    budget: '5억 5천만원',
    deadline: '2025-08-30',
    publishedDate: '2025-08-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 72,
    title: 'VR 콘텐츠 제작 지원 사업',
    organization: '문화체육관광부',
    budget: '4억 2천만원',
    deadline: '2025-09-15',
    publishedDate: '2025-08-10',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 73,
    title: '산업 안전 VR 시뮬레이션 시스템 개발',
    organization: '고용노동부',
    budget: '6억 3천만원',
    deadline: '2025-08-25',
    publishedDate: '2025-08-02',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 74,
    title: '가상현실 기반 의료 훈련 시스템 구축',
    organization: '보건복지부',
    budget: '7억 8천만원',
    deadline: '2025-09-10',
    publishedDate: '2025-08-15',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 75,
    title: 'VR 전시관 체험 시스템 구축',
    organization: '국립중앙박물관',
    budget: '3억 9천만원',
    deadline: '2025-08-20',
    publishedDate: '2025-08-01',
    status: '물품',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 76,
    title: '가상현실 기반 도시 계획 시스템 개발',
    organization: '국토교통부',
    budget: '8억 5천만원',
    deadline: '2025-09-05',
    publishedDate: '2025-08-08',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 77,
    title: 'VR 국방 훈련 시뮬레이터 개발',
    organization: '국방부',
    budget: '12억 7천만원',
    deadline: '2025-08-28',
    publishedDate: '2025-08-03',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 78,
    title: '가상현실 기반 재난 대응 훈련 시스템',
    organization: '행정안전부',
    budget: '6억 8천만원',
    deadline: '2025-09-20',
    publishedDate: '2025-08-18',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 79,
    title: 'VR 체험관 구축 사업',
    organization: '서울특별시',
    budget: '5억 2천만원',
    deadline: '2025-08-15',
    publishedDate: '2025-08-01',
    status: '공사',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 80,
    title: '가상현실 기반 관광 서비스 개발',
    organization: '한국관광공사',
    budget: '4억 6천만원',
    deadline: '2025-09-25',
    publishedDate: '2025-08-20',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 블록체인/암호화폐 관련 공고 (신규_공용_개인_2024_11_30)
  {
    id: 81,
    title: '블록체인 기반 공공 서비스 플랫폼 구축',
    organization: '행정안전부',
    budget: '9억 5천만원',
    deadline: '2025-12-15',
    publishedDate: '2025-11-20',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 82,
    title: '암호화폐 거래 모니터링 시스템 개발',
    organization: '금융위원회',
    budget: '7억 2천만원',
    deadline: '2025-11-30',
    publishedDate: '2025-11-10',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 83,
    title: '블록체인 기반 물류 추적 시스템 구축',
    organization: '해양수산부',
    budget: '6억 8천만원',
    deadline: '2025-12-10',
    publishedDate: '2025-11-15',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 84,
    title: '디지털 자산 관리 시스템 개발',
    organization: '한국은행',
    budget: '8억 3천만원',
    deadline: '2025-12-05',
    publishedDate: '2025-11-05',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 85,
    title: '블록체인 기반 신원 인증 시스템 구축',
    organization: '과학기술정보통신부',
    budget: '5억 7천만원',
    deadline: '2025-11-25',
    publishedDate: '2025-11-01',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 86,
    title: '암호화폐 과세 시스템 개발',
    organization: '국세청',
    budget: '6억 4천만원',
    deadline: '2025-12-20',
    publishedDate: '2025-11-18',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 87,
    title: '블록체인 기반 전자 투표 시스템 구축',
    organization: '중앙선거관리위원회',
    budget: '7억 9천만원',
    deadline: '2025-11-28',
    publishedDate: '2025-11-03',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 88,
    title: '분산원장 기술 연구개발 사업',
    organization: '한국인터넷진흥원',
    budget: '10억 2천만원',
    deadline: '2025-12-25',
    publishedDate: '2025-11-25',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 89,
    title: '블록체인 기반 저작권 관리 시스템 개발',
    organization: '문화체육관광부',
    budget: '5억 3천만원',
    deadline: '2025-11-20',
    publishedDate: '2025-11-01',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 90,
    title: '스마트 계약 플랫폼 구축 사업',
    organization: '법무부',
    budget: '7억 1천만원',
    deadline: '2025-12-30',
    publishedDate: '2025-11-30',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },

  // 로봇/자동화 관련 공고 (신규_공용_개인_2025_02_18)
  {
    id: 91,
    title: '스마트 팩토리 로봇 시스템 구축',
    organization: '산업통상자원부',
    budget: '14억 5천만원',
    deadline: '2026-03-15',
    publishedDate: '2026-02-20',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 92,
    title: '공공시설 자동화 시스템 도입',
    organization: '행정안전부',
    budget: '6억 8천만원',
    deadline: '2026-02-28',
    publishedDate: '2026-02-10',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 93,
    title: '의료용 로봇 시스템 개발',
    organization: '보건복지부',
    budget: '11억 3천만원',
    deadline: '2026-03-10',
    publishedDate: '2026-02-15',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 94,
    title: '물류 자동화 시스템 구축',
    organization: '우정사업본부',
    budget: '9억 7천만원',
    deadline: '2026-03-05',
    publishedDate: '2026-02-05',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 95,
    title: '로봇 활용 재난 대응 시스템 개발',
    organization: '소방청',
    budget: '8억 5천만원',
    deadline: '2026-02-25',
    publishedDate: '2026-02-01',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 96,
    title: '스마트 농업 자동화 시스템 구축',
    organization: '농림축산식품부',
    budget: '7억 2천만원',
    deadline: '2026-03-20',
    publishedDate: '2026-02-18',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 97,
    title: '로봇 교육 시스템 개발',
    organization: '교육부',
    budget: '5억 9천만원',
    deadline: '2026-02-28',
    publishedDate: '2026-02-03',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
  {
    id: 98,
    title: '자율주행 로봇 시범 사업',
    organization: '서울특별시',
    budget: '10억 6천만원',
    deadline: '2026-03-25',
    publishedDate: '2026-02-25',
    status: '용역',
    bidType: '사전 규격',
    isFavorite: false,
  },
  {
    id: 99,
    title: '산업용 로봇 고도화 사업',
    organization: '중소벤처기업부',
    budget: '12억 8천만원',
    deadline: '2026-02-15',
    publishedDate: '2026-02-01',
    status: '물품',
    bidType: '입찰 공고',
    isFavorite: false,
  },
  {
    id: 100,
    title: '스마트 도시 자동화 시스템 개발',
    organization: '국토교통부',
    budget: '15억 4천만원',
    deadline: '2026-03-30',
    publishedDate: '2026-02-28',
    status: '용역',
    bidType: '입찰 공고',
    isFavorite: true,
  },
];

// 임시 cost
export const DUMMY_BID_DATA_WITH_COST: (BidItem & { cost: number })[] = DUMMY_BID_DATA.map(bid => ({
  ...bid,
  cost: [100000000, 300000000, 500000000, 1000000000][Math.floor(Math.random() * 4)],
}));
